// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var loaderUtils, path, pp;

  path = require('path');

  pp = require('preprocess');

  loaderUtils = require('loader-utils');

  module.exports = function(source) {
    var context, extension, processed, ref;
    if (typeof this.cacheable === "function") {
      this.cacheable();
    }
    context = (loaderUtils.parseQuery(this.query)) || {};
    context.src = this.resourcePath;
    context.srcDir = this.context;
    context.NODE_ENV = context.NODE_ENV || 'development';
    ref = path.extname(this.resourcePath || '').split('.'), extension = ref[ref.length - 1];
    processed = pp.preprocess(source, context, extension);
    return this.callback(null, processed);
  };

}).call(this);
